Implement brownout protection for lift
Team694/turbo-guacamole pull request #93
Opened 2019-03-11 21:22 UTC by getmeoutt

2019-03-11 22:37 UTC, PrathamRawat requested changes

2019-03-11 22:37 UTC, PrathamRawat commented on src/main/java/frc/robot/Robot.java
> +            lift.disableCurrentLimit();
I'm worried this code can potentially slow down our robot loop time: in the article Justin linked, I think it mentioned that setting motor controller settings can take time. @justinkim does this sound accurate?

2019-03-11 22:37 UTC, PrathamRawat commented on src/main/java/frc/robot/RobotMap.java
> +    double CV_SPEED = 0; // Speed that stays the same through movements
These shouldn't be under the Fangs Solenoid Divider, and you shouldn't really be changing these anyways

2019-03-11 22:37 UTC, PrathamRawat commented on src/main/java/frc/robot/commands/LiftMoveCommand.java
> +        Robot.isLiftRunning = false;
I don't believe this will work as the lift move command is a default command. Try setting this boolean only when the lift speed is explicitly set to 0 ( or close to it bc double magic)

2019-03-11 22:37 UTC, PrathamRawat commented on src/main/java/frc/robot/subsystems/Lift.java
> +    }
Will this code take care of the high spikes in motor current when the motor initially starts up?

2019-03-11 22:37 UTC, PrathamRawat commented on src/main/java/frc/robot/Robot.java
> +            drivetrain.disableCurrentLimit();
We don't want to disable current limit on the drivetrain at all really, the reason we initially had it there was to prevent tripping breakers on the PDP that would cause us to lose control of our drivetrain for the entirety of our match

2019-03-12 01:15 UTC, justinkim commented on src/main/java/frc/robot/Robot.java
> +            lift.disableCurrentLimit();
A single `set` type call is not of concern. Watch out for loops or methods that will call many `set` or `get` type methods in a single DS control loop.

2019-03-12 21:52 UTC, bryanlai00 commented on src/main/java/frc/robot/RobotMap.java
> +    double CV_SPEED = 0; // Speed that stays the same through movements
The code was modified due to merge conflicts since this branch was overlooked 1-2 months ago. It will be fixed

2019-03-12 21:54 UTC, bryanlai00 commented on src/main/java/frc/robot/RobotMap.java
> +    double CV_SPEED = 0; // Speed that stays the same through movements
These constants aren't used anymore

2019-03-12 22:13 UTC, bryanlai00 commented on src/main/java/frc/robot/commands/LiftMoveCommand.java
> +        Robot.isLiftRunning = false;
This was fixed by setting the constant in the methods of Lift

2019-03-12 22:30 UTC, bryanlai00 commented on src/main/java/frc/robot/Robot.java
> +            drivetrain.disableCurrentLimit();
Fixed*

2020-10-19 00:41 UTC, closed without merging